Don't accept fuzz when patching
When testing and applying patches, set fuzz=0 so that patches must apply
exactly.  Also set "-f" to avoid interactive questions, and reorder so
that patches are tested before the output directory is created.

Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

diff --git a/livepatch-build b/livepatch-build
--- a/livepatch-build
+++ b/livepatch-build
@@ -257,23 +257,22 @@ echo
 
 if [ "${SKIP}" != "build" ]; then
     [ -e "${OUTPUT}" ] && die "Output directory exists"
-    mkdir -p "${OUTPUT}" || die
-
-    echo "Testing patch file..."
     cd "$SRCDIR" || die
-    patch -s -N -p1 --dry-run < "$PATCHFILE" || die "source patch file failed to apply"
+    patch -s -N -p1 -f --fuzz=0 --dry-run < "$PATCHFILE" || die "Source patch file failed to apply"
+
+    mkdir -p "${OUTPUT}" || die
 
     echo "Perform full initial build with ${CPUS} CPU(s)..."
     build_full
 
     echo "Apply patch and build with ${CPUS} CPU(s)..."
     cd "$SRCDIR" || die
-    patch -s -N -p1 < "$PATCHFILE" || die
+    patch -s -N -p1 -f --fuzz=0 < "$PATCHFILE" || die
     build_special patched
 
     echo "Unapply patch and build with ${CPUS} CPU(s)..."
     cd "$SRCDIR" || die
-    patch -s -R -p1 < "$PATCHFILE" || die
+    patch -s -R -p1 -f --fuzz=0 < "$PATCHFILE" || die
     build_special original
 fi
 
